//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomAttributesDataBaseFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CustomAttributesEntities : DbContext
    {
        public CustomAttributesEntities()
            : base("name=CustomAttributesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attributes> Attributes { get; set; }
        public virtual DbSet<FullTable> FullTable { get; set; }
        public virtual DbSet<Persons> Persons { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
